### ISSUE TITLE
Bajar la posición de la malla

### ISSUE THREAD

**Issue by gabrielperales** [Loycus/landing-page#14]

**Comment by gabrielperales** [comment]
@fannysm la malla está pegada a la parte de abajo. Lo que ocurre es que el tamaño original de la malla era 1024 x 214px, pero entonces en una pantalla normal se cortaba por los lados, asi que como es vectorial la escalé a 2048 x 428px por eso se sube más.

Si no quieres que suba tanto me tienes que pasar una malla nueva más ancha.

**Comment by gabrielperales** [comment]
Así es como quedaba a 1024 x 214 px: 

![captura de pantalla 2017-05-26 a las 13 36 57](https://cloud.githubusercontent.com/assets/1859128/26493297/ea9f4bc8-4218-11e7-9997-eae4debc77ad.png)

Si la ves bien @fannysm , puedes pasarme una de 2048 x 214 px .

**Comment by fannysm** [comment]
Sería un punto intermedio entre las 2, te paso una malla más ancha

**Comment by fannysm** [comment]
Aquí la tienes 
[red.zip](https://github.com/Loycus/landing-page/files/1031743/red.zip)
