### ISSUE TITLE
Btn Back to Top

### ISSUE THREAD

**Issue by fannysm** [Loycus/landing-page#17]
Incluir el botón back to top.
_Puedes ver el diseño en la pantalla de Landing de https://zpl.io/Z2YPo_

**Comment by gabrielperales** [comment]
@fannysm me falta el svg de la flecha mirando para arriba.

**Comment by fannysm** [comment]
Aquí tienes el icono
[ico_top.svg.zip](https://github.com/Loycus/landing-page/files/1037503/ico_top.svg.zip)
