### ISSUE TITLE
Añadir botón "Únete" en la sección de equipo

### ISSUE THREAD

**Issue by gabrielperales** [Loycus/landing-page#22]
El botón debe llevar un enlace a las ofertas de trabajo de linkedIn
![captura de pantalla 2017-06-01 a las 16 41 51](https://cloud.githubusercontent.com/assets/1859128/26685256/d922b6e8-46e9-11e7-96e0-871337afd36e.png)

**Comment by fannysm** [comment]
El botón irá a https://www.linkedin.com/company/loycus-social-network-s.a.
