### ISSUE TITLE
Bloque Sobre Loycus > Animación

### ISSUE THREAD

**Issue by fannysm** [Loycus/landing-page#27]
- [x] Subir la posición de la animación para que la grua tire los iconos por encima del título de "coming soon" (ver imagen)
- [x] Cambiar gif por este  [animTeaser.gif.zip](https://github.com/Loycus/landing-page/files/1047239/animTeaser.gif.zip)

<img width="1073" alt="captura de pantalla 2017-06-02 a las 11 06 30" src="https://cloud.githubusercontent.com/assets/28979359/26719111/8f6493ba-4783-11e7-9a24-1ff733496f20.png">

**Comment by gabrielperales** [comment]
@fannysm la animación nueva descuadra las posiciones de todo
