### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by fannysm** [Loycus/landing-page#31]
- [x] Cuando llegas al footer, el mapa tiene que hacer una animación de zoom y una vez posicionado, indicar el punto en el que está la oficina (ver [demoTeaser.mp4.zip](https://github.com/Loycus/landing-page/files/1047570/demoTeaser.mp4.zip))
- [x] Poner el icono de linkedin adjunto - [ico_linkedin.svg.zip](https://github.com/Loycus/landing-page/files/1047571/ico_linkedin.svg.zip)
- [x] Aumentar el interlineado 
- [x] La línea blanca de separación del footer tiene que tener una opacidad del 10% y tiene que el ancho del contenido de la página
- [x] Los textos que están en negro, ponerlos en el color principal al 80%

<img width="1056" alt="captura de pantalla 2017-06-02 a las 13 59 24" src="https://cloud.githubusercontent.com/assets/28979359/26724826/c07887c8-479b-11e7-8aa9-f9f909a7f322.png">

**Comment by fannysm** [comment]
@gabrielperales Hacer más grande el icono de linkedin

**Comment by gabrielperales** [comment]
@fannysm está como en el diseño: 32 x 32 px.
