### ISSUE TITLE
Botón Top

### ISSUE THREAD

**Issue by fannysm** [Loycus/landing-page#34]
Hacer que no baje hasta el bottom de la página sino que se quede como en diseño

<img width="1082" alt="captura de pantalla 2017-06-06 a las 14 05 53" src="https://cloud.githubusercontent.com/assets/28979359/26828346/59b730ce-4ac1-11e7-82c5-c0bbdade2caa.png">

**Comment by gabrielperales** [comment]
@fannysm eso voy a poder hacerlo.
