### ISSUE TITLE
Form > Envío Mail

### ISSUE THREAD

**Issue by fannysm** [Loycus/landing-page#37]
- [x] Poner con la tipografía Poppins, color principal

**Comment by gabrielperales** [comment]
@fannysm dónde?

**Comment by fannysm** [comment]
<img width="436" alt="captura de pantalla 2017-06-02 a las 13 06 33" src="https://cloud.githubusercontent.com/assets/28979359/26832669/753bf672-4ad0-11e7-8980-dab8e76eb8ff.png">
