### ISSUE TITLE
Cabecera > Ajustar elementos

### ISSUE THREAD

**Issue by fannysm** [Loycus/landing-page#42]
Ajustar los márgenes de los elementos para que no se solapen

Adjunto pantallazo del ordenador portátil de Gonzalo

![image001](https://user-images.githubusercontent.com/28979359/27023643-bfdad540-4f53-11e7-9ba7-e7996e2304bb.png)

**Comment by gabrielperales** [comment]
@fannysm  sabes que resolución usa en su ordenador?
