### ISSUE TITLE
Equipo > Btn Únete

### ISSUE THREAD

**Issue by fannysm** [Loycus/landing-page#47]
Crear una micro interacción en rollOver del tipo https://material.uplabs.com/posts/material-design-buttons-interface-web

**Comment by gabrielperales** [comment]
No estoy usando ninguna libreria para *material design*, así que tendría que hacer algo como esto https://codepen.io/440design/pen/iEztk

**Comment by fannysm** [comment]
Se podría hacer algo como la animación del button 6 de https://codepen.io/megaFIKUS/pen/ZWoEvr ?

**Comment by gabrielperales** [comment]
Si, y sería bastante más fácil. Eso reduciria el tiempo de desarrollo a 15-30min
