### ISSUE TITLE
Footer > Mapa

### ISSUE THREAD

**Issue by fannysm** [Loycus/landing-page#48]
- [ ] Ajustar la posición de la viñeta con el logo de localización para que quede como en diseño
- [ ] Cuando subes la pantalla y vuelves a bajarla a la posición del footer, se recoloca el mapa y hace una pequeña vibración

<img width="1060" alt="captura de pantalla 2017-06-12 a las 10 44 11" src="https://user-images.githubusercontent.com/28979359/27025816-19887838-4f5c-11e7-8358-0a19754b79c9.png">

**Comment by gabrielperales** [comment]
La vibración no se exactamente por qué se produce. Encontrar el error y solucionarlo me puede llevar bastante tiempo.

**Comment by fannysm** [comment]
Cuidado con la posición del localizador

**Comment by andyindahouse** [comment]
Arreglado. 👍

**Comment by fannysm** [comment]
Gabi xfa no me cierres los issues, que aún no los he visto
 
Fanny Sánchez
 
Social Network Loycus S.A.
C/ Leganitos 47, 4ª planta
www.loycus.com
