### ISSUE TITLE
 Versión mobile > Ruleta

### ISSUE THREAD

**Issue by fannysm** [Loycus/landing-page#55]
Se podría hacer que todas la caja blanca de cada palabra en la ruleta sea clicable?

**Comment by gabrielperales** [comment]
Si, si quieres lo cambio, pero según me explicasteis era al pinchar las flechas.

**Comment by fannysm** [comment]
En mobile creo que supone una mejora de la usabilidad, ya que el tamaño de la flecha es muy pequeño
