### ISSUE TITLE
Versión mobile > Red Cabecera

### ISSUE THREAD

**Issue by fannysm** [Loycus/landing-page#56]
Hacer que no desaparezcan los puntos en la versión mobile

<img width="273" alt="captura de pantalla 2017-06-12 a las 11 15 49" src="https://user-images.githubusercontent.com/28979359/27027143-88e623de-4f60-11e7-952e-d155d319bab7.png">

**Comment by gabrielperales** [comment]
Tienen que desaparecer porque están posicionados de manera absoluta y quedarían fuera de la pantalla, y entonces tendríamos scroll horizontal que quedaría horrible.

**Comment by fannysm** [comment]
Pendiente de ver otra alternativa
