### ISSUE TITLE
Versión mobile > Equipo

### ISSUE THREAD

**Issue by fannysm** [Loycus/landing-page#57]
Centrar la foto en el fondo para que quede como en diseño y que se dejen de ver los laterales

<img width="223" alt="captura de pantalla 2017-06-12 a las 11 23 15" src="https://user-images.githubusercontent.com/28979359/27027408-942278d2-4f61-11e7-8fbc-4de4776be75b.png">

**Comment by gabrielperales** [comment]
Parece una tontería, pero hacer intenté que se alinee bien en movil y en desktop y me costó. Creo que lo más fácil es hacer dos botones bien alineados y mostrarlos u ocultarlos dependiendo de si es movil o desktop.

**Comment by fannysm** [comment]
Utilizar esta imagen [equipoLoycus_mv.zip](https://github.com/Loycus/landing-page/files/1067693/equipoLoycus_mv.zip)
