### ISSUE TITLE
Pop up

### ISSUE THREAD

**Issue by fannysm** [Loycus/landing-page#59]
- [x] Aumentar el espaciado entre el botón X y la caja (ver diseño)
- [x] Aumentar padding arriba y abajo (ver diseño)
 
<img width="663" alt="captura de pantalla 2017-06-07 a las 15 48 01" src="https://user-images.githubusercontent.com/28979359/27027770-e9fc5506-4f62-11e7-952d-87449498e137.png">

**Comment by fannysm** [comment]
Cuando se envía el email, salta hasta 3 veces la animación

**Comment by gabrielperales** [comment]
eso debería ser un issue diferente.
