### ISSUE TITLE
Añadir meta tags de título y descripción

### ISSUE THREAD

**Issue by gabrielperales** [Loycus/landing-page#61]
```html
<title> Compras, ofertas, descuentos, novedades y promociones cerca de ti</title>
<meta name="description" content="Tu red social de compras">
```

**Comment by fannysm** [comment]
@andyindahouse cambiar por
<title> Loycus - Tu red social de compras</title>
<meta name=“description” content=“Tu red social de compras”>

**Comment by andyindahouse** [comment]
Entiendo que el meta tag se dejaría igual, no?

**Comment by gabrielperales** [comment]
te refieres al `meta name="description"`? Imagino que si, creo que solo quiere que cambies el `<title></title>`
